### ISSUE TITLE
Performance: avoid regexp unless it is needed

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-filter_leeloolxp#1]
`preg_match_all()` is more expensive than plain `strpos()`. It is generally recommended for all filters that are based on a keyword presence, to first perform a quick `strpos()`-like check and only if a keyword is present somewhere, only then perform the actual regexp-based search & replace.

In your case, you may want to check if the substring `[[LEELOOLXP_` is present and if not, return early from the filter method.

**Comment by anayleeloolxp** [comment]
Hello @mudrd8mz Thanks for the suggestion, have added that condition in filter and created a new release.
